sudo: false
matrix:
  fast_finish: true
  include:
  - python: '3.5'
    env: TOXENV=lint
cache:
  directories:
  - "$HOME/.cache/pip"
language: python
script:
- flake8 graphql_subscription_manager --max-line-length=120
- pylint graphql_subscription_manager --max-line-length=120
deploy:
  provider: pypi
  user: dahoiv
  password:
    secure: 196c3duVPUW1uRO1o4sUmuY38Vf9LInKWc0T1GoiTClTYIbcZC6ZWQ9UyRTRXGf80N8AJxaI2MWCdiA7yJSNM4nFQfQiJ49k5iLGxKOoFJynoityQilh5jY26A3RgKTHbGiytBxttyvwyZMeIi32tRl0m83zjSnD0xN5u7GMz0yPqY4ySb0oWBE9MlYwsFjgA46Y6IpZ+kuEXRLPpFwGtxtP31KqJjbgwM2eoCMbQsnDEVmeLPZNtiHKCvCGYzZmDrWwEiLBJGK2TEX+8pivZktD3lcfrOlQHQ7enPdkfAW0OkF5/zr+G8O2O0bzFUSMxBw5WcGHTStnYcRzjxEuFYA8MVVvrmB0nK37HtbAHErfEjm3O5ZNBqV0/qSptBqLTDjBeQuuCsTIkOQ91D+UvIDH/u2C3TJGhUvIOLnspytDh2nO3RuoxjsfKF5Mrjh37tigpC6oxedpl+tkfx6u+nXimeMd46c/lHbooczOT2zXpUAxuJdlXROhl41IfaV39Vo0tSHp0Id9G4s+JcZuVSaciTeeAPu8pIBIo9RQ68G4kDP1npkFY/XPvgjsTMDoluTJu3kAZ6sQImjd1Ru1YmUGh6DPCOJOQzTfvWdNyJL11JZnEppMfwkac3FD9FKcAqjhYf1uyfKyNRh8D7Nje28PFaEZT+65pNqj7gvEFSM=
  on:
    tags: true
    repo: Danielhiversen/PyGraphqlWebsocketManager
    branch: master
